# backend/services/doctor-service/src/main/resources/application.yml
spring:
  application:
    name: doctor-service
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 60000   # 连接超时 60s
            read-timeout: 300000
server:
  port: 8003
internal:
  service-key: ${INTERNAL_SERVICE_KEY:}
