# backend/services/doctor-service/src/main/resources/application.yml
spring:
  application:
    name: doctor-service
  profiles:
    active: dev
  config:
    import: optional:nacos:doctor-service.yml

server:
  port: 8003