spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  application:
    name: payment-service
  profiles:
    active: dev
  config:
    import: optional:nacos:payment-service.yml

server:
  port: 8005