# backend/services/auth-service/src/main/resources/application.yml
spring:
  application:
    name: auth-service
  profiles:
    active: dev
  config:
    import: optional:nacos:auth-service.yml

server:
  port: 8002