# backend/services/patient-service/src/main/resources/application.yml
spring:
  application:
    name: patient-service
  profiles:
    active: dev
  config:
    import: optional:nacos:patient-service.yml

server:
  port: 8004