# backend/services/admin-service/src/main/resources/application.yml
spring:
  application:
    name: admin-service
  profiles:
    active: dev
  config:
    import: optional:nacos:admin-service.yml

server:
  port: 8000