# backend/gateway-server/src/main/resources/application.yml
spring:
  profiles:
    include: route   # 引入 route 配置文件
  application:
    name: gateway-server
  config:
    import: optional:nacos:gateway-server.yml

server:
  port: 80