spring:
  application:
    name: ai-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true
  config:
    import: optional:nacos:ai-service.yml
  datasource:
    url: jdbc:postgresql://cloudbrainmed.rwlb.rds.aliyuncs.com:5432/cloudbrainmed?ssl=false
    username: iris
    password: Abc39173551
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY:}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: deepseek-v4-flash
          temperature: 0.1
          max-tokens: 512
    embedding:
      api-key: ${DASHSCOPE_API_KEY:}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      model: text-embedding-v4
      dimensions: 1024
  vector-loader:
    pdf:
      enabled: true
  pgvector:
    enabled: true
    dimension: 1024 # 根据你的嵌入模型调整维度
    initialize-schema: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3000ms

server:
  port: 8001
